### ISSUE TITLE
Does not properly load option file.

### ISSUE THREAD

**Issue by GimpMaster** [astyle-format/vscode-format#18]
I get an error when trying to run this with an option file specified. I believe the issue is that AStyle 3.1 (2018) uses --options NOT --option as you specify here:

https://github.com/astyle-format/vscode-format/blob/master/src/extension.js#L39

**Comment by ankun6** [comment]
How to use file .astylerc ?

**Comment by WiRight** [comment]
@ankun6 in unix system keep `.astylerc` file in yout HOME dir

**Comment by WiRight** [comment]
@GimpMaster Thank you for your issue! I'll check it

**Comment by WiRight** [comment]
@ankun6 Also you can use preferences `astyleFormat.astylerc`
